// Autogenerated from Pigeon (v17.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonShift {
  var title: String
  var startTimeMills: Int64
  var endTimeMills: Int64
  var description: String

  static func fromList(_ list: [Any?]) -> PigeonShift? {
    let title = list[0] as! String
    let startTimeMills = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let endTimeMills = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let description = list[3] as! String

    return PigeonShift(
      title: title,
      startTimeMills: startTimeMills,
      endTimeMills: endTimeMills,
      description: description
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      startTimeMills,
      endTimeMills,
      description,
    ]
  }
}

private class CalendarHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonShift.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class CalendarHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonShift {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class CalendarHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return CalendarHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return CalendarHostApiCodecWriter(data: data)
  }
}

class CalendarHostApiCodec: FlutterStandardMessageCodec {
  static let shared = CalendarHostApiCodec(readerWriter: CalendarHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol CalendarHostApi {
  func syncShiftsToSystem(shifts: [PigeonShift], completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class CalendarHostApiSetup {
  /// The codec used by CalendarHostApi.
  static var codec: FlutterStandardMessageCodec { CalendarHostApiCodec.shared }
  /// Sets up an instance of `CalendarHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: CalendarHostApi?) {
    let syncShiftsToSystemChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar.CalendarHostApi.syncShiftsToSystem", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      syncShiftsToSystemChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let shiftsArg = args[0] as! [PigeonShift]
        api.syncShiftsToSystem(shifts: shiftsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      syncShiftsToSystemChannel.setMessageHandler(nil)
    }
  }
}
