// Autogenerated from Pigeon (v17.1.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonShiftIslandData {
  var shiftName: String
  var startTimeMills: Int64
  var endTimeMills: Int64
  var colorHex: String

  static func fromList(_ list: [Any?]) -> PigeonShiftIslandData? {
    let shiftName = list[0] as! String
    let startTimeMills = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let endTimeMills = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let colorHex = list[3] as! String

    return PigeonShiftIslandData(
      shiftName: shiftName,
      startTimeMills: startTimeMills,
      endTimeMills: endTimeMills,
      colorHex: colorHex
    )
  }
  func toList() -> [Any?] {
    return [
      shiftName,
      startTimeMills,
      endTimeMills,
      colorHex,
    ]
  }
}
private class LiveActivityHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return PigeonShiftIslandData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class LiveActivityHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonShiftIslandData {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class LiveActivityHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return LiveActivityHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return LiveActivityHostApiCodecWriter(data: data)
  }
}

class LiveActivityHostApiCodec: FlutterStandardMessageCodec {
  static let shared = LiveActivityHostApiCodec(readerWriter: LiveActivityHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LiveActivityHostApi {
  func startOrUpdateIsland(data: PigeonShiftIslandData) throws
  func stopIsland() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LiveActivityHostApiSetup {
  /// The codec used by LiveActivityHostApi.
  static var codec: FlutterStandardMessageCodec { LiveActivityHostApiCodec.shared }
  /// Sets up an instance of `LiveActivityHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LiveActivityHostApi?) {
    let startOrUpdateIslandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar.LiveActivityHostApi.startOrUpdateIsland", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startOrUpdateIslandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let dataArg = args[0] as! PigeonShiftIslandData
        do {
          try api.startOrUpdateIsland(data: dataArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startOrUpdateIslandChannel.setMessageHandler(nil)
    }
    let stopIslandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_calendar.LiveActivityHostApi.stopIsland", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopIslandChannel.setMessageHandler { _, reply in
        do {
          try api.stopIsland()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopIslandChannel.setMessageHandler(nil)
    }
  }
}
